"""Generate standalone Isaac Sim render scripts."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from .coordinates import arkit_cam_to_world_to_ros_optical, scale_intrinsics
from .io import load_phone_scene, write_json


ISAAC_RENDER_SCRIPT = r'''#!/usr/bin/env python3
"""Generated by PhoneSceneToIsaac. Run with: isaacsim --no-window --python SCRIPT."""

from __future__ import annotations

import json
from pathlib import Path

from isaacsim import SimulationApp

CONFIG_PATH = Path(__file__).with_suffix(".json")
CONFIG = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))

simulation_app = SimulationApp({
    "headless": bool(CONFIG.get("headless", True)),
    "renderer": CONFIG.get("renderer", "RayTracedLighting"),
})

import numpy as np
import omni.replicator.core as rep
import omni.usd
from pxr import Gf, UsdGeom


def _as_numpy(data):
    if hasattr(data, "numpy"):
        data = data.numpy()
    return np.asarray(data)


def _write_png(path: Path, image: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    image = np.asarray(image)
    if image.ndim == 3 and image.shape[2] == 4:
        image = image[:, :, :3]
    image = image.astype(np.uint8, copy=False)
    try:
        from PIL import Image

        Image.fromarray(image).save(path)
    except Exception:
        import imageio.v3 as iio

        iio.imwrite(path, image)


def _matrix4(values):
    rows = np.asarray(values, dtype=np.float64).reshape(4, 4)
    return Gf.Matrix4d(
        rows[0, 0], rows[0, 1], rows[0, 2], rows[0, 3],
        rows[1, 0], rows[1, 1], rows[1, 2], rows[1, 3],
        rows[2, 0], rows[2, 1], rows[2, 2], rows[2, 3],
        rows[3, 0], rows[3, 1], rows[3, 2], rows[3, 3],
    )


ROS_OPTICAL_TO_USD_CAMERA = np.diag([1.0, -1.0, -1.0, 1.0])


def _ros_optical_to_usd_camera_pose(transform):
    return np.asarray(transform, dtype=np.float64).reshape(4, 4) @ ROS_OPTICAL_TO_USD_CAMERA


def _configure_camera(camera, frame, width, height):
    intrinsics = np.asarray(frame["intrinsics"], dtype=np.float64).reshape(3, 3)
    fx = float(intrinsics[0, 0])
    fy = float(intrinsics[1, 1])
    cx = float(intrinsics[0, 2])
    cy = float(intrinsics[1, 2])
    horizontal_aperture = 20.0
    focal_length = fx * horizontal_aperture / float(width)
    vertical_aperture = focal_length * float(height) / max(fy, 1e-9)
    horizontal_offset = (cx - float(width) * 0.5) * horizontal_aperture / float(width)
    vertical_offset = -(cy - float(height) * 0.5) * vertical_aperture / float(height)
    camera.GetProjectionAttr().Set("perspective")
    camera.GetFocalLengthAttr().Set(focal_length)
    camera.GetHorizontalApertureAttr().Set(horizontal_aperture)
    camera.GetVerticalApertureAttr().Set(vertical_aperture)
    camera.GetHorizontalApertureOffsetAttr().Set(horizontal_offset)
    camera.GetVerticalApertureOffsetAttr().Set(vertical_offset)
    camera.GetClippingRangeAttr().Set(Gf.Vec2f(0.05, float(CONFIG["max_depth_m"])))


def _set_camera_pose(camera_prim, camera_to_world_ros):
    usd_pose = _ros_optical_to_usd_camera_pose(camera_to_world_ros)
    xform = UsdGeom.Xformable(camera_prim)
    xform.ClearXformOpOrder()
    xform.AddTransformOp().Set(_matrix4(usd_pose))


def main():
    output_dir = Path(CONFIG["output_dir"]).expanduser().resolve()
    (output_dir / "rgb").mkdir(parents=True, exist_ok=True)
    (output_dir / "depth").mkdir(parents=True, exist_ok=True)

    ctx = omni.usd.get_context()
    ctx.open_stage(str(Path(CONFIG["scene_usd"]).expanduser().resolve()))
    for _ in range(30):
        simulation_app.update()
    stage = ctx.get_stage()

    camera_path = "/World/RenderCamera"
    camera = UsdGeom.Camera.Define(stage, camera_path)
    width = int(CONFIG["width"])
    height = int(CONFIG["height"])
    _configure_camera(camera, CONFIG["frames"][0], width, height)

    render_product = rep.create.render_product(camera_path, (width, height))
    rgb_annotator = rep.AnnotatorRegistry.get_annotator("rgb")
    depth_annotator = rep.AnnotatorRegistry.get_annotator("distance_to_image_plane")
    rgb_annotator.attach([render_product])
    depth_annotator.attach([render_product])

    manifest = []
    warmup = int(CONFIG.get("warmup_frames", 3))
    for frame in CONFIG["frames"]:
        _configure_camera(camera, frame, width, height)
        _set_camera_pose(camera.GetPrim(), frame["camera_to_world_ros"])
        for _ in range(warmup):
            rep.orchestrator.step()
            simulation_app.update()

        rgb = _as_numpy(rgb_annotator.get_data())
        depth = _as_numpy(depth_annotator.get_data()).astype(np.float32)
        if depth.ndim == 3:
            depth = depth[:, :, 0]
        depth[~np.isfinite(depth)] = 0.0
        depth = np.clip(depth, 0.0, float(CONFIG["max_depth_m"]))

        stem = f"{int(frame['frame_id']):06d}"
        rgb_path = output_dir / "rgb" / f"{stem}.png"
        depth_path = output_dir / "depth" / f"{stem}.npy"
        _write_png(rgb_path, rgb)
        np.save(depth_path, depth)
        manifest.append({
            "frame_id": int(frame["frame_id"]),
            "timestamp": float(frame["timestamp"]),
            "rgb": str(rgb_path.relative_to(output_dir)),
            "depth": str(depth_path.relative_to(output_dir)),
            "width": width,
            "height": height,
            "intrinsics": frame["intrinsics"],
            "camera_to_world_ros": frame["camera_to_world_ros"],
        })

    (output_dir / "metadata.json").write_text(
        json.dumps({
            "format": "phone_isaac_render",
            "format_version": 1,
            "scene_usd": CONFIG["scene_usd"],
            "width": width,
            "height": height,
            "max_depth_m": CONFIG["max_depth_m"],
        }, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    with (output_dir / "manifest.jsonl").open("w", encoding="utf-8") as stream:
        for entry in manifest:
            stream.write(json.dumps(entry, sort_keys=True) + "\n")

    simulation_app.close()


if __name__ == "__main__":
    main()
'''


def make_isaac_script(
    scene_root: Path | str,
    scene_usd: Path | str,
    script_path: Path | str,
    output_dir: Path | str,
    width: int = 1280,
    height: int = 720,
    frame_stride: int = 1,
    max_depth_m: float = 8.0,
    headless: bool = True,
) -> Path:
    scene = load_phone_scene(scene_root)
    if not scene.frames:
        raise ValueError(f"No frames in {scene.root}")
    scene_usd = Path(scene_usd).expanduser().resolve()
    if not scene_usd.exists():
        raise FileNotFoundError(scene_usd)
    script_path = Path(script_path).expanduser().resolve()
    output_dir = Path(output_dir).expanduser().resolve()
    if width <= 0 or height <= 0:
        raise ValueError("Render width and height must be positive")
    if frame_stride <= 0:
        raise ValueError("frame_stride must be positive")
    if max_depth_m <= 0.0:
        raise ValueError("max_depth_m must be positive")
    script_path.parent.mkdir(parents=True, exist_ok=True)

    frames: list[dict] = []
    for frame in scene.frames[::frame_stride]:
        cam_to_world_ros = arkit_cam_to_world_to_ros_optical(frame.camera_to_world_arkit)
        intrinsics = scale_intrinsics(
            frame.intrinsics,
            frame.image_width,
            frame.image_height,
            width,
            height,
        )
        frames.append(
            {
                "frame_id": frame.frame_id,
                "timestamp": frame.timestamp,
                "intrinsics": intrinsics.tolist(),
                "camera_to_world_ros": cam_to_world_ros.tolist(),
            }
        )
    if not frames:
        raise ValueError("No frames selected for Isaac rendering")

    config = {
        "scene_usd": str(scene_usd),
        "output_dir": str(output_dir),
        "width": int(width),
        "height": int(height),
        "max_depth_m": float(max_depth_m),
        "headless": bool(headless),
        "renderer": "RayTracedLighting",
        "warmup_frames": 3,
        "frames": frames,
    }
    write_json(script_path.with_suffix(".json"), config)
    script_path.write_text(ISAAC_RENDER_SCRIPT, encoding="utf-8")
    script_path.chmod(0o755)
    return script_path
